# Generated by Django 5.0.3 on 2024-03-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_projectupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectUpload',
        ),
    ]
